#!/usr/bin/env python
# NODERUNNERS v3 - this source IS the laser-eye bear behind bars.
# The whole "WE'RE ALL GOING TO JAIL" poster is zlib+base85-packed into the
# silhouette below (beams = the laser eyes); blanks/dots are not code.
# Readable source: noderunners_v3_unpacked.py  ->  rebuild with: python repack_bear.py noderunners_v3_unpacked.py noderunners_v3.py
import base64 as _b,zlib as _z
_=r"""
          c-pmDQFGhI5q{^d                                                                                          xWJP!K!Fqhk`hH(
          u4S2#mB>;nIniWT                                                                                          js^seBq9)C0Z_6M
          `^8V~TkXWjOlSHd                                                                                          +P-wA5BVz{|B`;Y
          2N0wrN=hb$C<?c?                                                                                          x4XByx4XA`@X6{l
          iC24mxGKYQF}X}f                                                                                          QCNB)D&>msqP`yv
     TVk3HDoutw$Q~gM#G!a5+Tuuj                                                                                iT4A3I~GFh0Dd4o<8d2rJNTY0
     16^@m6BUt;q|i><50Bbndw*Z-                                                                                9_}6NikFAt^X<KTO-!OBm9cOW
     ;fDD5V>gw3v3<O=w<jjP^khr8                                                                                !gGfJs)q>=WB=Q4gG+JYrz7!n
     @8u4Niv8{5HU#;)eJlokjNOPd                                                                                V(wlPhcZq~5yfsel$9u~^a9sA
     GsVZZKZ^@+jK^+#mMGe8*ayq~                                                                                y|3C>I1ST&bP-mCus6i9oCwEq
          *08BBA~})4P@WUP&<E}9I2_4wRowhA<x!eWlGf^K81-d54N0bIDAS85KAXpN<5ai<(h3QmDX4cz@V-p^Vc5Go{!HjQJC;#p%Kx9I<c}v2L`g15
          bNEgDu`~q?G%`gWN~3Y<h1g<HDN3rqOyyYDG^3Qpmn~XZO`yMNT8*U_g#&*$jioL_<!oCTI~%a&D^E^R(dIvX6t={~O_EY+?*!D>>f)C?4}?#e
          g=_R7Rr{;<!AlUy<*m|-PDV7vh6$q@B{~3jl&6rRnIeu{_MhC%^kn4rWq(sVeDV;)0yhBzc_|HEx#TH5ZEqg|yHg^uG$B6z_`UjE7kX|=Gc)`d
          ?B+#Rr)TS~&isncoD{#7oVZTo{l_2Q@n_j0HT(WX0p2~yCvW^@)8F61b?MTZxz6_ee)%W2%Wt)8Ce4kX_qQzjGh^KN{r)%Oc7re8;WEn*yL9R%
          ZXnZCCbu1;U;32#av;WMdXh$y#AvZZ1RCh)*@&KV980Sz`~lt`2}{Tzk;2XZkA<xO=QI346pJ&&6~XyK4`i4zsMvE<Id+?fA)wCFowM$y=mF9z
               AS-rvVS$oiOY|1$(34`7eqM2nRlQenk-UU$TtkXwI*mi2dv3?-uIOG5e=0mM$|(ucu@%^6uss7i3hXf0A#g!FBdSEM
               *xgPhbOs-ko*o^Z98lyx(>r?AvP`{JHyz8gZNo72YRxhAjWx5;G;0<E@TS{!%WSTh^)-exvBt*GcADmTlR$RW)E$iM
               reoT)u4|MIkG2nX+oT7lzK(EBU(TAbDRz$9+b<Nn4p6O$FQ<-)ljnOc)q>g@O{gzS>>jnhCb-?OKuCQxjndKKetYL|
               A2Z)+syxtILa{Z4=Ec$-1HkMsz8Lu_AuyLWrQ_$@&)U2cCk<e$id_o~zURT3!-MxcsH?#{9ys+kC3e-oAC6MElZW(b
               v<hpoF`Y)E;>|3{hE$;3iflv$$}C7Ud+^V`4o~bY5>+0;4l?r(<sR%EGv`pg!LH%X)Aa&(JZb9Q9Lcf!O1I3hACeTN
               AEqq10dtC*rtIZY4ow+KDFZ*%^TV6a(do4IPH>baZXY8Q1r@<Z5LOKUAn@v{aOPc96IwYCD_Fk5?>Zr2
               S+1eTJJaLnBInY(;4<bFAMM!S10VB&Cmh8_XU4q?V|8_bRVU{aS3Mb`R?~r#vsJ>Xb&FKHN~d{+spr9p
               IH{_ovRJiL)2Q!W>V|>QWm3w5N1x(Vt2mn4<HwIN^IiXqc((oZF%{aohX6c!^hhh#Y;Dn^Tvuv|O$(Oe
               TLpf(Tm~LtSHua5|2-T6z_bMeq$4*(NzHpktxM&UE2#3-W)&A|JUNE9&eyqm6neMURkz3f-qa8JxiWjw
               jmd$Oy{R5kF|Oyvr(P7$R0rY1#?eIZ5(qwm0tSVY24HJeH?Jw1;v3fwXdw#W<Z?WgY3zH#?V-38WcFC9
               -4hlnL_bM&IDja_T@_DKgh$5DnYS3Z<8^_ref;5HnYx1@BC#~B`b~rrLO4cuMgg9~G-zW*#_&ctPs|$&
               X={<?)zssSi2o-L;0fZA8nHBQwHYc&RCOm43M#o&-pI&z6{YvyFCou3{HNIORqBM7(SINkFLqOGkbHz3
               zk=HP9Jj&L4N#dQc&IxbQdK3812RSsh-fe?=Vv9rWSZ(ef+p-Ym$ZX07oQ~Q_}xYI;f@I2*o6$IV;R%s
               Au+D2apeqk1kO6$9fPogahJ{vG}0=@ptPV=Fe6oDn+`(7nZzXDL$-L0N4$QmApjAyHV+k=QQUY)FGA_1
               #6$u=lnLEq0?AI^HSs&sgxl}y*(_o?<K`wvXgf5);**q`Duz@{h9pcgM`sdDmuPAl#KX-xJk#cYC!#GL
               a)&^OZLu%*2`fvrb7;GK8Q&8JVi%y7f`ZWJSg^Nj!Bu9n=t@$z7$-KfJ=`VZfrt?0B-T$wh#z`Ov{?Z#
               hj~NKLz@)_cd<Ff^%fBiVb0#5TQuE6Z{FOp{=&U^%_Ww5X^(-oG$<CtRE`?Bf0{~;RUbe6pi##A_~EZw
               8OMNMf6}^mp~-hNiG#*q49HR#!c^>gIojW@)A+lV6`tggf_e3#7{W1a<=!iEz$|7AT*QT|%^k3#m>|cK
               ^b)x~9{QomqPXQ#*6pYOI+v!^4vXMR{^S`n)6wf@4K-`sT(j|K!*r;C#fbhQmC&5CrY36^&(>^n%_4Bq
               tQ*}Tgy6hcbODGFL8$s5X$%e|^wx>H95J(4G7l2kfB*fncGVPl+L+r0En2AG6}k!lrPA;BxBu`Zie0LN
                    DOailTB6nq$)l#Js@oLL7hp!|>EY3{HuX3XiSQ3EfYo6~*bP=BQyZn7ZLZ%H!Vhne  =P2|S
                    U6-DpdJ%a--cv!Im{7N9jF6`)1Na{$ym6BE^LkO5M&rD#w^%Ebxc>)DWX39LF21@w   H;Tlh
                    ASVWyAlqf3?I&=i&khf%cNEH3@QWKLVI3zj0?r5+SzRAW%0!7Cqp<Ms8{7DsUl+ry    +;n?D
                    uq!bfL(sctS3KN&_^!85V<OT{Dc)Ku8GhMc4Gl6OfjxlLQU<F%`h~3Fij5j#=kN$-     -rYYW
                    (|-5H#P2=2Y0x9oSb5AQ5X0bdGAd!?<OZZ_Lp<IRj@lKCt4S26`kB1k!fm0~cZF;T     NriuL
                    iX<!}JqVv77Y`?#UUeo0FGDp(_oNU1(14(TxPY4Cq{8>75C7DRx%|6$Dhs767N#Hz      5}zw6
                   n>3L*2puHIurN(j`z%!j!oX&%v?_cUrgf)5s`J{FzQOVvrCEP~LkJ;f452876T=pAZ       @`o~X
                   I*vC86!^RwJHJ<-*qmLT;t(+$8L3V5?ZB#BkPCkXoOenW)jo&N&91%R}s}%0@sr|JQ        xZ))R
                  Z#>g^zL)XSY%&iQO?53GC)Nk#p4=H)lsOxK%&t`$JR#bc3^$IipPAtjT*3BQdE7i1f<         tb$(}
                  C^^K8wbs7P`IG<-JhkC@N`DTYT8zIFZ;OC-YhE7C^2&q7e)=Vy>oY1u?Mfqt}E!#H4r          ^2qT<
                  9cFMYmEhD6=$gZv+f{u;41EvUsMyQE-hQtM#EsBwKfCV)eVCW0{j0U@Vzq`FOWpg8V1           n?6J6
                 uw^?8zuJsY|&P@K+mf&xIP=egFs=7S5-=6ZjK+#R%Lk!Le2+&Gf+7@H+-2T>?D5!eS@3           SOggE
                 g)WJHFwDfB|_w;NG5PHu4%L6bmJPnVr22Ob+6_<#dp#s-4|y$p|lJi_X_UyG#Vyd1@yW            F{o9U
                J&TL{RaE-u?0*VvByU{-W^p~3jr<%95lx^R4hs4*TA_N|?ZirQ(Q_b?6M@ttb#Pvm0zMA             M2U1u
                ^C<-f+NRka<XTy~bPhBjI4t%cp^EhMTxaFd1io8-Zbaxz*@N(O~#sElY`CAMyv^`_}qOp              IyGbo
                TaV?Ot>V@haWCvxakdZ~0zdqe8trlg}AwEO-xH3hyKeS67wGwOzw?%nj^(Zrk^vMnz8Rp               8uWdq
               Zk!QDy8Zsly1W&CnNt|XSap}Q_sw<^42-fG+0D3jXDTJBqV%Rns<o3c*D!pz+GLPo0`=j3                N~-VT
               2LXe=G>tT9GENW%zCR#i#VEDW0jR#vu>paA&bPW(&v4&t3n2cYCW1znQPptVRq^Ha^QCCx                 p3pus
              B45HO QI^akFl+0L*17Z5_OSk^*fAF?30Rv);)H~`y07Ibf@=lxpAMZ6|sd?GR$2{HIwIK3                 -4^LI
              3$fS@ BVf@EB7dLsL0~|8om0h^wjFS6CDM{(zFA_PxxQ8>GC*^lsM}>aTcyMH=WH-`|2~+P                  (~1sS
              t7-tb O#;p2A`(d=t_$VE4W9@T&=vrFk3KJ(P43c$pu3|4WYTRYY<G6k-kWQyT(a?#G+F!z                   =Bk)Y
             -N{<?  BDHQ$je^j#{E5NTF2ALoTB*O?_3-BA%)apW>(p;Bza{wDyqF8+Y&Z_TOKTNdK#i;J                    3Zxib
             9zcO@  9C+gD5?Uu^gqs|n~w................................................                     .....
            .....   .................................................................                      .....
            .....   .................................................................                       .....
            ..................                                                  ...............             .....
           ...................                                                  ...............              .....
           ...................                                                  ...............               .....
          ....................                                                  ...............                .....
          ....................                                                  ...............                 .....
         ..... ...............                                                  ...............                  .....
         ..... ...............                                                  ...............                   .....
         ..... ...............                                                  ...............                    .....
        .....  ...............                                                  ...............                    .....
        .....  ...............                                                  ...............                     .....
       .....                                                                                                         .....
       .....                                                                                                          .....
       .....                                                                                                           .....
      .....                                                                                                             .....
      .....                                                                                                              .....
     .....                                                                                                               .....
     .....                                                                                                                .....
     .....                                                                                                                 .....
    .....                                                                                                                   .....
    .....                                                                                                                    .....
   .....                                                                                                                      .....
   .....                                                                                                                       .....
  .....                                                                                                                         .....
  .....                                                                                                                         .....
  .....                                                                                                                          .....
 .....                                                                                                                            .....
 .....                                                                                                                             .....
.....                                                                                                                               .....
.....                                                                                                                                .....
.....                                                                                                                                 .....
....                                                                                                                                  .....
....                                                                                                                                   .....
...                                                                                                                                     ....
...                                                                                                                                      ...
"""
exec(_z.decompress(_b.b85decode("".join(_.split()).replace(".",""))).decode("utf-8"))